### ISSUE TITLE
Please specify the license of the font and codes

### ISSUE THREAD

**Issue by simnalamburt** [Dalgona/neodgm#1]
By default these fonts and codes all "All right reserved" to you by the [Berne Convetion] and [WIPO Copyright Treaty]. Software and fonts published without a license do not grant people to benefit or redistribute in [most countries].

Please specify the license of this project. Since this project is consist of both font and project, the separate licenses should be applied to both.

[Berne Convetion]: https://en.wikipedia.org/wiki/Berne_Convention
[WIPO Copyright Treaty]: https://en.wikipedia.org/wiki/WIPO_Copyright_Treaty
[most countries]: https://en.wikipedia.org/wiki/World_Intellectual_Property_Organization

**Comment by Dalgona** [comment]
라이센스를 적용하는건 검토하고 있었습니다. 상기시켜 주셔서 감사합니다.
