### ISSUE TITLE
neodgm를 homebrew-cask-fonts에 추가하고 싶습니다

### ISSUE THREAD

**Issue by nyeong** [Dalgona/neodgm#11]
- [homebrew-cask-fonts](https://github.com/Homebrew/homebrew-cask-fonts)

homebrew를 통해 글꼴을 관리하는 저장소입니다. Neo둥근모를 각각

- font-neodunggeunmo
- font-neodunggeunmo-code

라는 이름으로 등록하고 싶은데 괜찮을까요?

**Comment by Dalgona** [comment]
네! 🚀🚀

**Comment by Dalgona** [comment]
감사합니다~

**Comment by Dalgona** [comment]
homebrew-cask-fonts의 PR이 머지된 것을 확인했습니다. 😊 슬슬 이 리포지토리의 README에 (지원 되는) 패키지 관리자를 통해 글꼴을 설치하는 법에 대한 설명을 추가하려고 하는데, 기여자분의 GitHub 아이디나 SNS(트위터) 연락처를 문서에 포함해도 괜찮으신가요?

**Comment by nyeong** [comment]
네 괜찮습니다.
제 깃허브 아이디는 @nyeong이고, 트위터는 [@compiztab](https://twitter.com/compiztab)입니다.

**Comment by Dalgona** [comment]
추가했습니다!
