### ISSUE TITLE
웹폰트 지원

### ISSUE THREAD

**Issue by ChangJoo-Park** [Dalgona/neodgm#17]
안녕하세요 만들어주신 폰트를 잘 쓰고 있습니다

웹 앱 등에서 사용할 수 있도록 Google Fonts  등으로 배포할 가능성이 있으실까요?

**Comment by Dalgona** [comment]
현재 jsDelivr 등의 CDN을 통해 웹 폰트를 이용하실 수 있도록 [neodgm-webfont](https://github.com/Dalgona/neodgm-webfont) 리포지토리를 제공하고 있으며, 아직 Google Fonts 등의 다른 서비스에 웹 폰트를 게시할 계획은 없습니다.

**Comment by ChangJoo-Park** [comment]
아 이미 준비해두셨군요 알려주신 방법으로 사용해보겠습니다 감사합니다
