### ISSUE TITLE
cask 2.7.0 이상일 경우, 명령어 변경건 README 반영

### ISSUE THREAD

**Issue by 9m1i9n1** [Dalgona/neodgm#18]
안녕하세요! 정말 잘 쓰고있습니다.
사소한 부분이지만 가이드 부분에 `cask`를 통한 설치가 버전에 따라 명령어가 달라지게 된 것같아 보완하면 좋을것 같아 이슈올려봅니다!

`cask` 반영시, 2.7.0 이상일 경우 readme 가이드에 있는 기존 명령어가 `deprecated` 되어 사용이 불가한 부분이 있는것같아요!

`brew install --cask font-neodunggeunmo` 의 명령어로 사용이 되어야 하는 부분이 있어 요부분 보완해주시면 차후에 더 사용하기 좋을것 같아요! 🥰

최근에 다시 폰트 설치하게 되면서 발견했네요. 관련 문서는 [이곳](https://github.com/Homebrew/discussions/discussions/340)입니다!

**Comment by Dalgona** [comment]
감사합니다! 저도 최근에 Homebrew cask를 설치하면서 해당 변경 사항을 알게 되었는데, README 문서를 수정할 생각은 못 했었네요. 😂 최대한 빨리 반영해 놓겠습니다.
