### ISSUE TITLE
neodgm은 혹시 파워라인을 지원하나요

### ISSUE THREAD

**Issue by KaiNiGHt** [Dalgona/neodgm#19]
지원되지 않는다면 지원하게 해주실수 있을까요..?
파워라인 쓰는 터미널에서 쓰면 너무 이쁠거같네요!
**파워라인 만세**

**Comment by Dalgona** [comment]
Neo둥근모 및 Neo둥근모 Code에는 아래와 같은 Powerline용 특수 문자가 기본적으로 포함되어 있습니다. 

<img width="332" alt="스크린샷 2021-06-11 오후 7 21 02" src="https://user-images.githubusercontent.com/2667858/121671963-2b25fd00-caea-11eb-987a-61fc01882376.png">

Neo둥근모에서 지원하는 전체 문자 목록은 [글꼴 견본 페이지](https://neodgm.dalgona.dev/specimen.html)에서 확인해 주세요.
