### ISSUE TITLE
좋은 폰트 감사합니다.

### ISSUE THREAD

**Issue by easylogic** [Dalgona/neodgm#3]
멋진 폰트 만들어 주셔서 감사합니다. 

많이 많이 쓰여지면 좋겠네요 ^^

**Comment by Dalgona** [comment]
감사합니다. 그리고 여기는 문제점이나 개선 사항을 제기하는 곳이기 때문에 그 외의 의견은 이메일(<dalgona@hontou.moe>)로 보내주시기 바랍니다 😀
