### ISSUE TITLE
demo가 보이지 않습니다

### ISSUE THREAD

**Issue by joshua-qa** [Dalgona/neodgm#4]
![s__2670609](https://cloud.githubusercontent.com/assets/18359200/24195100/cae8708a-0f3b-11e7-9f3a-2ddfafe2a323.jpg)
<img width="391" alt="demo" src="https://cloud.githubusercontent.com/assets/18359200/24195107/d1b519d6-0f3b-11e7-9a35-b5b5f3928671.png">

스크린샷 참고 부탁드립니다.
감사합니다.

**Comment by BasixKOR** [comment]
` GET https://camo.githubusercontent.com/a61b6aa4e9642e0193c151e26efabfb9a4da3522…6f73747265616d2e6b722f7265732f6e656f64676d2f6e656f64676d5f64656d6f2e706e67 404 (Not Found)`이라는 오류가 뜨네요. 이미지 링크만 수정하면 될 것 같아요 😃

**Comment by vbalien** [comment]
Github 프록시 서버 문제 같습니다.

https://help.github.com/articles/about-anonymized-image-urls/

관련 문서입니다.

**Comment by Dalgona** [comment]
최근에 서버 VPS를 이전하고 나서 이미지 파일을 업로드를 안 했네요... 시간 날 때 수정하겠습니다 ㅠㅠ

**Comment by Dalgona** [comment]
문제 해결되었습니다. :rocket:

**Comment by joshua-qa** [comment]
수정 사항이 정상적으로 반영되었음을 확인하였습니다.
감사합니다.
