### ISSUE TITLE
NBSP 문자 추가 부탁드립니다.

### ISSUE THREAD

**Issue by gwangyi** [Dalgona/neodgm#7]
PuTTY에 네오 둥근모 폰트를 적용해서 써봤더니 0x00A0 문자가 이상하게 찍혀 나옵니다.

그래서 빈 문자로 폰트를 추가해서 폰트를 수정해봤더니 제대로 나오는 것을 볼 수 있었습니다.

추가로, 폰트 사이즈가 12 이하에서는 i와 l이 똑같은 모양으로 보이고 powerline symbol에 빈틈이 생기는것 같던데 혹시 이유를 아시나요?;;

**Comment by Dalgona** [comment]
네 아까 PR 확인했는데 수업중이라 제대로 응답을 못해드렸네요 ㅠㅠ NBSP 문제는 저도 이전에 확인했던 문제로, 보내주신 PR은 시간 나는대로 확인해 보겠습니다.

폰트 사이즈와 관련해서는... 이 폰트가 태생이 비트맵 폰트라서 글자 크기가 16px(96 dpi 디스플레이에서 12pt)의 배수가 아니면 일그러져 보이는 게 정상입니다.

**Comment by Dalgona** [comment]
[v1.2.1](https://github.com/Dalgona/neodgm/releases/tag/v1.2.1)
