### ISSUE TITLE
make 시 에러

### ISSUE THREAD

**Issue by Quiple** [Dalgona/neodgm#8]
```
elixir ./makesvg.exs fnt
Converting fnt/basic-latin.fnt................................................................................................................................done.
Converting fnt/block-elements.fnt................................done.
Converting fnt/box-drawing.fnt................................................................................................................................done.
Converting fnt/braille-patterns.fnt................................................................................................................................................................................................................................................................done.
Converting fnt/dingbats.fnt..............................done.
Converting fnt/enclosed-alphanumerics.fnt........................................................................done.
Converting fnt/general-punctuation.fnt..................................done.
Converting fnt/geometric-shapes.fnt................................................................................................done.
Converting fnt/hangul-compatibility-jamo.fnt...................................................done.
Converting fnt/hangul-jamo-source.fnt............................................................................................................................................................................................................................................................................................................................................................done.
Converting fnt/lat1-supplment.fnt...............................................................................................done.
Converting fnt/powerline-symbols.fnt.......done.
Converting fnt/trigrams.fnt........done.
fatal: Not a valid object name HEAD
python ./font.py
Expected a version string as the first argument.
Makefile:13: recipe for target 'ttf' failed
make: *** [ttf] Error 1
```
이걸로 다른 비트맵 폰트를 빌드해보고 싶어서 만져보는 중인데요,
`Makefile:13: recipe for target 'ttf' failed`에서 막힌 것 같은데 원인이 뭘지 알 수 있을까요ㅠㅠ

**Comment by Dalgona** [comment]
현재 빌드 프로그램은 다른 분들이 사용할 때를 고려하지 않고 만들었습니다. 빠른 시일 내에 프로그램을 개선하고 빌드 설명서를 준비하겠습니다 ㅠㅠ




---- On Mon, 16 Sep 2019 10:00:50 +0900 notifications@github.com wrote ----


elixir ./makesvg.exs fnt

Converting fnt/basic-latin.fnt................................................................................................................................done.

Converting fnt/block-elements.fnt................................done.

Converting fnt/box-drawing.fnt................................................................................................................................done.

Converting fnt/braille-patterns.fnt................................................................................................................................................................................................................................................................done.

Converting fnt/dingbats.fnt..............................done.

Converting fnt/enclosed-alphanumerics.fnt........................................................................done.

Converting fnt/general-punctuation.fnt..................................done.

Converting fnt/geometric-shapes.fnt................................................................................................done.

Converting fnt/hangul-compatibility-jamo.fnt...................................................done.

Converting fnt/hangul-jamo-source.fnt............................................................................................................................................................................................................................................................................................................................................................done.

Converting fnt/lat1-supplment.fnt...............................................................................................done.

Converting fnt/powerline-symbols.fnt.......done.

Converting fnt/trigrams.fnt........done.

fatal: Not a valid object name HEAD

python ./font.py

Expected a version string as the first argument.

Makefile:13: recipe for target 'ttf' failed

make: *** [ttf] Error 1



이걸로 다른 비트맵 폰트를 빌드해보고 싶어서 만져보는 중인데요,
Makefile:13: recipe for target 'ttf' failed에서 막힌 것 같은데 원인이 뭘지 알 수 있을까요ㅠㅠ

**Comment by Quiple** [comment]
감사합니다!!
비트맵 폰트를 아웃라인 폰트로 변환하려고 여러 방법을 찾아봤는데 확실한 방법을 모르겠어서..
정말로 도움이 될 것 같습니다ㅠㅠ

**Comment by Dalgona** [comment]
이 리포지토리의 `README.md` 파일에 빌드 과정에 대한 설명을 추가했습니다. 한 번 해 보시고 문제가 있는지 확인해 주세요. 😄💦

**Comment by Dalgona** [comment]
충분한 시간 동안 응답이 없으셔서 이 이슈를 닫겠습니다.
